apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  clusterIP: None
  selector:
    app: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-0
  labels:
    app: alertmanager
spec:
  selector:
    statefulset.kubernetes.io/pod-name: alertmanager-0
  ports:
  - port: 9093
    name: web
  - port: 9094
    name: cluster
  - port: 9094
    name: cluster-udp
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-1
  labels:
    app: alertmanager
spec:
  selector:
    statefulset.kubernetes.io/pod-name: alertmanager-1
  ports:
  - port: 9093
    name: web
  - port: 9094
    name: cluster
  - port: 9094
    name: cluster-udp
    protocol: UDP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
spec:
  selector:
    matchLabels:
      app: alertmanager
  serviceName: alertmanager
  replicas: 2
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.21.0
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yml"
          - "--cluster.peer=alertmanager-0:9094"
          - "--cluster.peer=alertmanager-1:9094"
        ports:
        - containerPort: 9093
          name: http
        - containerPort: 9094
          name: cluster-tcp
        - containerPort: 9094
          name: cluster-udp
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
      volumes:
      - name: config-volume
        configMap:
         name: alertmanager-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global: {}
    receivers:
      - name: alertdog
        webhook_configs:
          - url: http://alertdog:9796/webhook
            send_resolved: true
      - name: default-receiver
    route:
      receiver: default-receiver
      routes:
        - match:
            alertname: Watchdog
          group_interval: 30s
          repeat_interval: 1m
          receiver: alertdog
