name: Docker PR

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Quay
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: errm/alertdog:pr-${{ env.GITHUB_HEAD_REF_SLUG }},quay.io/errm/alertdog:pr-${{ env.GITHUB_HEAD_REF_SLUG }}
          platforms: linux/amd64,linux/arm64
